### ISSUE TITLE
4. schedule input

### ISSUE THREAD

**Issue by cknguyen123** [CSE-210/Exercise-Buddy-App#10]
As a developer, I want users to have schedule details inputted before finding matches, so that this data can be used for matching algorithm

**Comment by LoukikNaik** [comment]
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/25
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/26
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/30
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/32
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/33
