### ISSUE TITLE
15. apply additional preference filters

### ISSUE THREAD

**Issue by YinanQiao00** [CSE-210/Exercise-Buddy-App#16]
As a user, I want the ability to apply additional preference filters to narrow student matches, so I can get new matches corresponding to my different interests.

**Comment by mjalbert99** [comment]
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/29
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/34
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/37
