### ISSUE TITLE
11. menu option

### ISSUE THREAD

**Issue by YinanQiao00** [CSE-210/Exercise-Buddy-App#17]
As a user, I want a menu option to directly access different pages of the app, so I can easily navigate through the app.

**Comment by LoukikNaik** [comment]
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/53
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/55
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/57
