### ISSUE TITLE
12. change/update my account details/ preferences

### ISSUE THREAD

**Issue by YinanQiao00** [CSE-210/Exercise-Buddy-App#18]
As a user, I want to be able to change/update my account details/ preferences in my settings so that I can update my account.

**Comment by LoukikNaik** [comment]
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/79
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/81
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/82
