### ISSUE TITLE
13. change/update my contact information

### ISSUE THREAD

**Issue by YinanQiao00** [CSE-210/Exercise-Buddy-App#20]
As a user, I want to be able to change/update my contact information in my settings so that I can update contact information I choose to disclose.

**Comment by LoukikNaik** [comment]
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/60
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/63
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/65

**Comment by mjalbert99** [comment]
Changed how contact info is now stored. grabs user email from database or they can store contact info in their bio.
