### ISSUE TITLE
Task: Redirect user to the last page accessed in the stack memory

### ISSUE THREAD

**Issue by mjalbert99** [CSE-210/Exercise-Buddy-App#22]
Make sure it goes to previous or homepage when clicked

**Comment by cknguyen123** [comment]
Could not incorporate as an interface as it would need to refactor multiple classes already using this function. It only requires implementing the 2 functions below.


Add lines in oncreate():
// showing the back button in action bar
        ActionBar actionBar = getSupportActionBar();
        actionBar.setDisplayHomeAsUpEnabled(true);

Add function:
    /** Back button: function is not to save edited data to firebase **/
    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                this.finish();
                return true;
        }
        return super.onOptionsItemSelected(item);
    }
