### ISSUE TITLE
6. log into my account

### ISSUE THREAD

**Issue by YinanQiao00** [CSE-210/Exercise-Buddy-App#8]
As a previous user, I want to be able to log into my account, so I dont not have to create a new account each time I use the app.

**Comment by YinanQiao00** [comment]
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/70
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/72
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/73
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/74
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/76
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/77

**Comment by mjalbert99** [comment]
Implemented the UI and back end interactions of buttons and text inputs

**Comment by mjalbert99** [comment]
Implemented login and logout feature
