### ISSUE TITLE
9. reset my password

### ISSUE THREAD

**Issue by YinanQiao00** [CSE-210/Exercise-Buddy-App#9]
As a previous user, I want to be able to reset my password in my user profile page so if I forget it or want to change it I have the option.

**Comment by amquach00** [comment]
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/35
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/67
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/50
- [x] https://github.com/CSE-210/Exercise-Buddy-App/issues/75

**Comment by mjalbert99** [comment]
Cant do expresso test to see if password changed so marked done
